apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: service-g-async
spec:
  # Add external load balancer
  # *Only supported by some cloud providers*
  type: LoadBalancer
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: app-g-async
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: app-a-async
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: app-a-async
---
apiVersion: v1
kind: Service
metadata:
  # The unique Service instance/name
  name: app-b-async
spec:
  ports:
    - name: http
      port: 5000
      targetPort: 5000
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: app-b-async
